- hosts: localhost
  tasks:
    - name: Add Docker Repo
      become: true
      command:
        cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
        warn: false
    - name: Install packages
      become: true
      package:
        name:
          - bat
          - curl
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - fzf
          - git
          - gnome-tweak-tool
          - go
          - hub
          - jq
          - kubernetes-client
          - make
          - nodejs
          - openssh
          - ruby
          - tmux
          - util-linux-user
          - vim
          - xclip
          - zsh
          - zsh-syntax-highlighting
          - zsh-autosuggestions
    - name: Download Dotfiles
      git:
        repo: git@github.com:jingweno/dotfiles.git
        dest: ~/.dotfiles
    - name: Link Dotfiles
      file:
        src: '~/.dotfiles/{{ item }}'
        dest: '~/{{ item }}'
        state: link
      loop:
        - .gemrc
        - .gitignore
        - .gitconfig
        - .irbrc
        - .spacevim
        - .tmux.conf
        - .zshrc
        - .zshrc.linux
    - name: Start Docker
      become: true
      command: systemctl enable docker
    - name: Add User To Docker Group
      become: true
      command: gpasswd -a ${USER} docker
    - name: Enable Night Light
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: "true"
    - name: Enable Flathub repository
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - name: Install Spotify
      command: flatpak install --assumeyes flathub com.spotify.Client
    - name: Install Discord
      command: flatpak install --assumeyes flathub com.discordapp.Discord
    - name: Install Slack
      command: flatpak install --assumeyes flathub com.slack.Slack
