- hosts: localhost
  tasks:
    # dnf packages start
    - name: Add extra dnf repos
      become: true
      command:
        cmd: 'dnf config-manager --add-repo {{ item }}'
        warn: false
      loop:
        - https://download.docker.com/linux/fedora/docker-ce.repo
        - https://cli.github.com/packages/rpm/gh-cli.repo
    - name: Install packages
      become: true
      package:
        name:
          - bat
          - curl
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - fzf
          - gh
          - git
          - gnome-tweak-tool
          - go
          - hub
          - jq
          - kubernetes-client
          - make
          - nodejs
          - openssh
          - ruby
          - tmux
          - util-linux-user
          - vim
          - xclip
          - zsh
          - zsh-syntax-highlighting
          - zsh-autosuggestions
    # dnf packages end
    #
    - name: Change Shell to Zsh
      command: chsh -s /usr/bin/zsh

    # Oh My Zsh starts
    - name: Remove Oh My Zsh
      file:
        path: ~/.oh-my-zsh
        state: absent
    - name: Download Oh My Zsh
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/oh-my-zsh-install.sh
    - name: Install Oh My Zsh
      script: /tmp/oh-my-zsh-install.sh
    # Oh My Zsh ends
    
    # space-vim starts
    - name: Download space-vim
      get_url:
        url: https://raw.githubusercontent.com/liuchengxu/space-vim/master/install.sh
        dest: /tmp/space-vim-install.sh
    - name: Install space-vim
      script: /tmp/space-vim-install.sh
    # space-vim ends

    # Dotfiles starts
    - name: Download Dotfiles
      git:
        repo: git@github.com:jingweno/dotfiles.git
        dest: ~/.dotfiles
    - name: Link Dotfiles
      file:
        src: '~/.dotfiles/{{ item }}'
        dest: '~/{{ item }}'
        state: link
        force: true
      loop:
        - .gemrc
        - .gitignore
        - .gitconfig
        - .irbrc
        - .spacevim
        - .tmux.conf
        - .zshrc
        - .zshrc.linux
    # Dotfiles ends
    
    # Docker starts
    # Ref: https://www.linuxuprising.com/2019/11/how-to-install-and-use-docker-on-fedora.html
    - name: Start Docker
      become: true
      command: systemctl enable --now docker
    - name: Add User To Docker Group
      become: true
      command: usermod -aG docker ${USER}
    - name: Drop to cgroup1 for Docker
      become: true
      command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
    - name: Fix Docker Network
      become: true
      command: firewall-cmd --permanent --zone trusted --add-interface docker0
    # Docker ends
    
    - name: Enable Night Light
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: "true"

    # Flathub starts
    - name: Enable Flathub repository
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - name: Install Flathub Packages
      command: flatpak install --assumeyes flathub {{ item }}
      loop:
        - com.discordapp.Discord
        - com.dropbox.Client
        - com.slack.Slack
        - com.spotify.Client
    # Flathub ends
